# Generated by Django 3.1.3 on 2020-11-07 16:42

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='ID')),
                ('login', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Login')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('salary', models.DecimalField(decimal_places=3, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Salary')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
